### PR TITLE
fix #53 iteritems() -> items()

### LINKED ISSUE #53: incompatibility py2 vs py3 [`iteritems`]
from [documentation](http://krypy.readthedocs.org/en/latest/), the code below does not pass with Python 3 and raises, at least, the error:
```
  File "...krypy/krypy/utils.py", line 1408, in get_ops
    for op, count in ops.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

However, the test (TravisCI/nose) should pass, which means that the coverage is not enough.

```python
#!/usr/bin/env python
# coding: utf8

from numpy import diag, linspace, ones, eye
from krypy.linsys import LinearSystem, Minres
from krypy.deflation import DeflatedMinres
from krypy.recycling import RecyclingMinres

A = diag(linspace(1, 2, 20))
A[0, 0] = -1e-5
b = ones(20)
linear_system = LinearSystem(A, b, self_adjoint=True)

solver = Minres(linear_system)

dsolver = DeflatedMinres(linear_system, U=eye(20, 1))

rminres = RecyclingMinres(vector_factory='RitzApproxKrylov')
rsolver1 = rminres.solve(linear_system)
rsolver2 = rminres.solve(linear_system)

from matplotlib.pyplot import semilogy, show, legend
semilogy(solver.resnorms, label='original')
```

### PR DESCRIPTION
**Pull request by zimoun**

### CODE REVIEW

**Comment by andrenarchy** [comment]
Can you fix the same issue in `krypy/recycling/factories.py`?

**Comment by andrenarchy** [comment]
Now this PR also contains changes related to `ConvergenceError`. Can you remove the last commit?

**Comment by zimoun** [comment]
ok, I am trying

**Comment by andrenarchy** [comment]
Now it's one more commit. You can get rid of the last 2 commits by running
```
git reset --hard HEAD~2
```
**Warning:** this will remove the last 2 commits from your branch forever.

Check with 
```
git log
```
if your commit history looks good. Last commit should be da4379f. Then you have to use
```
git push --force
```
because it will permanently remove these commits.

**Comment by zimoun** [comment]
I did not know that PR works with branch and not commit.
Sorry.

Close this PR, 
I created two branches `fix53` and `converr`, then it seem easier to PR.

**Comment by andrenarchy** [comment]
Merged via #56.

**Pull request closed without merging**
